FROM node:18-slim

WORKDIR /usr/src/app

# Upgrade system packages to reduce vulnerabilities before installing dependencies
RUN apt-get update && apt-get upgrade -y && apt-get clean

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD ["node", "dist/main.js"]